from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from .analyzer import (
    generate_candidates,
    interactive_select,
    make_default_selections,
    rank_candidates,
    save_analysis_outputs,
)
from .boundary import refine_candidate_boundaries
from .console import configure_console
from .models import ProjectPaths, ReelSelection, TranscriptDocument
from .ollama_client import OllamaClient
from .renderer import render_reels
from .scene_analysis import Scene, load_or_detect_scenes
from .subtitles import chunk_transcript
from .timecode import parse_timecode
from .transcription import (
    LocalSubtitleProvider,
    TranscriptionProvider,
    WhisperXConfig,
    WhisperXProvider,
    YouTubeSubtitleProvider,
    load_or_transcribe,
)
from .utils import fail, read_json, write_json
from .youtube import download_youtube_video


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="reelmaker",
        description="Generate vertical reels from a local video using local transcription and Ollama.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    for name in ["all", "analyze", "render", "transcribe", "subtitles", "scenes"]:
        add_common_args(sub.add_parser(name))
    return parser


def add_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--youtube-url", help="YouTube URL used to extract subtitles, and optionally video.")
    parser.add_argument("--source-video", type=Path, help="Local source video. Preferred for quality.")
    parser.add_argument("--download-video", action="store_true", help="Download YouTube video if --source-video is not provided.")
    parser.add_argument("--subtitle-file", type=Path, help="Existing SRT/VTT file.")
    parser.add_argument("--subtitle-langs", default="fr.*,fr", help="yt-dlp subtitle language selector. Default avoids en.* to reduce YouTube 429 errors.")
    parser.add_argument("--output-dir", type=Path, default=Path("output"), help="Output directory.")

    parser.add_argument(
        "--transcription",
        choices=["auto", "subtitles", "whisperx"],
        default="auto",
        help="Transcript source. auto preserves SRT/YouTube when supplied, otherwise uses WhisperX for a local video.",
    )
    parser.add_argument("--force-transcription", action="store_true", help="Ignore transcript cache and transcribe again.")
    parser.add_argument("--whisper-model", default="large-v3", help="WhisperX ASR model. large-v3 favors French quality on a 12 GB GPU.")
    parser.add_argument("--whisper-language", default="fr", help="WhisperX language code, or auto for detection.")
    parser.add_argument("--whisper-device", choices=["auto", "cuda", "cpu"], default="auto", help="WhisperX device.")
    parser.add_argument("--whisper-compute-type", default="auto", help="WhisperX compute type. auto uses float16 on CUDA and int8 on CPU.")
    parser.add_argument("--whisper-batch-size", type=int, default=4, help="WhisperX batch size. Reduce if GPU memory is insufficient.")

    parser.add_argument("--ollama-url", default="http://localhost:11434", help="Ollama base URL.")
    parser.add_argument("--model", default="qwen3:4b", help="Ollama model. Default favors speed for local reel selection.")
    parser.add_argument("--temperature", type=float, default=0.2, help="Ollama temperature.")
    parser.add_argument("--num-ctx", type=int, default=16384, help="Ollama context window.")
    parser.add_argument("--ollama-timeout", type=int, default=600, help="Ollama HTTP timeout in seconds.")
    parser.add_argument("--ollama-num-predict", type=int, default=1024, help="Maximum tokens generated by Ollama per request.")
    parser.add_argument("--no-ollama-stream", action="store_true", help="Disable Ollama streaming for unstructured requests. Structured JSON requests are always non-streaming.")

    parser.add_argument("--target-count", type=int, default=10, help="Final reels count.")
    parser.add_argument("--shortlist-count", type=int, default=20, help="Shortlist count for validation.")
    parser.add_argument("--candidates-per-chunk", type=int, default=3, help="Max candidates proposed per transcript chunk.")
    parser.add_argument("--chunk-seconds", type=int, default=300, help="Transcript chunk size in seconds. Smaller chunks are safer for local models; larger chunks mean fewer Ollama calls.")
    parser.add_argument("--chunk-overlap-seconds", type=int, default=20, help="Transcript overlap between chunks.")
    parser.add_argument("--min-duration", type=int, default=18, help="Minimum reel duration in seconds after boundary refinement.")
    parser.add_argument("--target-duration", type=int, default=22, help="Preferred duration for short reels; boundaries may be expanded toward this value.")
    parser.add_argument("--max-duration", type=int, default=60, help="Maximum reel duration in seconds.")
    parser.add_argument("--pre-padding", type=float, default=0.25, help="Seconds added before the first subtitle cue when refining boundaries.")
    parser.add_argument("--post-padding", type=float, default=1.2, help="Seconds added after the selected speech boundary.")
    parser.add_argument(
        "--boundary-mode",
        choices=["auto", "words", "cues", "off"],
        default="auto",
        help="Cut refinement source. auto uses WhisperX word pauses when available, otherwise subtitle cues.",
    )
    parser.add_argument("--yes", action="store_true", help="Non-interactive: accept top ranked reels.")
    parser.add_argument("--ranking-mode", choices=["local", "ollama"], default="local", help="Ranking strategy. Local is much faster and avoids malformed LLM JSON.")
    parser.add_argument("--no-resume", action="store_true", help="Disable resume/cache of previous Ollama chunk results.")
    parser.add_argument("--force-ollama", action="store_true", help="Ignore cached Ollama chunk/ranking results and recompute.")

    parser.add_argument("--selected-reels", type=Path, help="JSON file generated by analyze; default: output-dir/selected_reels.json.")
    parser.add_argument("--no-render", action="store_true", help="For all/analyze: do not render videos.")
    parser.add_argument("--no-burn-subtitles", action="store_true", help="Render without burning subtitles into video.")
    parser.add_argument("--subtitle-font-size", type=int, default=60, help="Burned subtitle font size for 1080x1920 ASS subtitles.")
    parser.add_argument("--subtitle-margin-v", type=int, default=150, help="Vertical bottom margin for subtitles. Larger = higher above bottom.")
    parser.add_argument("--subtitle-wrap-width", type=int, default=23, help="Approximate subtitle characters per line before ASS wrapping.")
    parser.add_argument("--subtitle-max-lines", type=int, default=2, help="Maximum burned subtitle lines. Keeps reels readable on phones.")
    parser.add_argument("--subtitle-correction", choices=["off", "basic", "ollama"], default="basic", help="Subtitle cleanup mode. 'ollama' corrects selected reel captions with context and caches results.")
    parser.add_argument("--force-subtitle-correction", action="store_true", help="Ignore cached corrected subtitles and recompute them.")
    parser.add_argument("--crop-mode", choices=["center", "face", "motion", "smart", "scene-smart"], default="smart", help="Vertical crop mode. scene-smart recalculates smart framing for each detected shot.")
    parser.add_argument("--scene-detection", choices=["auto", "off"], default="auto", help="Scene detection used by scene-smart. auto uses local PySceneDetect; off falls back to one static smart crop.")
    parser.add_argument("--scene-threshold", type=float, default=27.0, help="PySceneDetect content threshold. Lower values detect more cuts.")
    parser.add_argument("--scene-min-frames", type=int, default=15, help="Minimum scene length in frames for PySceneDetect.")
    parser.add_argument("--force-scene-detection", action="store_true", help="Ignore scenes.json and detect shots again.")
    parser.add_argument("--fps", type=int, default=25, help="Output frame rate.")
    parser.add_argument("--end-card-seconds", type=float, default=0.0, help="Append a final YouTube call-to-action card. 0 disables it.")
    parser.add_argument("--end-card-style", choices=["short", "title", "full", "none"], default="short", help="Final card layout. short is recommended for Reels/TikTok.")
    parser.add_argument("--end-card-comment-text", default="Voir commentaire", help="Small text shown on the final card.")
    parser.add_argument("--episode-title", default="", help="Episode title shown on the final YouTube card and captions.")
    parser.add_argument("--youtube-cta", default="Suite sur YouTube", help="Text shown on the final YouTube card.")
    parser.add_argument("--crf", type=int, default=20, help="FFmpeg x264 CRF, lower means better quality/larger file.")
    parser.add_argument("--preset", default="medium", help="FFmpeg x264 preset.")


def resolve_source_video(args: argparse.Namespace, paths: ProjectPaths) -> Path:
    if args.source_video:
        if not args.source_video.exists():
            fail(f"Source video not found: {args.source_video}")
        return args.source_video
    if args.download_video and args.youtube_url:
        return download_youtube_video(args.youtube_url, paths.source_dir)
    fail("Provide --source-video, or add --download-video with --youtube-url.")


def choose_transcription_mode(args: argparse.Namespace) -> str:
    if args.transcription != "auto":
        return args.transcription
    if args.subtitle_file or args.youtube_url:
        return "subtitles"
    if args.source_video:
        return "whisperx"
    fail("Provide --source-video, --subtitle-file, or --youtube-url.")


def make_transcription_provider(args: argparse.Namespace, paths: ProjectPaths) -> TranscriptionProvider:
    mode = choose_transcription_mode(args)
    if mode == "subtitles":
        if args.subtitle_file:
            if not args.subtitle_file.exists():
                fail(f"Subtitle file not found: {args.subtitle_file}")
            return LocalSubtitleProvider(args.subtitle_file, paths.subtitles_dir)
        if args.youtube_url:
            return YouTubeSubtitleProvider(args.youtube_url, paths.subtitles_dir, args.subtitle_langs)
        fail("Transcription mode subtitles requires --subtitle-file or --youtube-url.")

    source_video = resolve_source_video(args, paths)
    return WhisperXProvider(
        source_video,
        WhisperXConfig(
            model=args.whisper_model,
            language=args.whisper_language,
            device=args.whisper_device,
            compute_type=args.whisper_compute_type,
            batch_size=args.whisper_batch_size,
        ),
    )


def load_transcript(args: argparse.Namespace, paths: ProjectPaths) -> TranscriptDocument:
    provider = make_transcription_provider(args, paths)
    try:
        document, reused = load_or_transcribe(
            provider,
            paths.output_dir,
            force=args.force_transcription,
        )
    except RuntimeError as exc:
        fail(str(exc))

    cache_text = "reused cache" if reused else "generated"
    print(
        f"Transcript {cache_text}: {len(document.cues)} cues, "
        f"{len(document.words)} timed words, provider={document.provider}"
    )
    return document


def make_client(args: argparse.Namespace) -> OllamaClient:
    return OllamaClient(
        base_url=args.ollama_url,
        model=args.model,
        temperature=args.temperature,
        num_ctx=args.num_ctx,
        timeout_seconds=args.ollama_timeout,
        num_predict=args.ollama_num_predict,
        stream=not args.no_ollama_stream,
    )


def load_scenes_for_render(args: argparse.Namespace, paths: ProjectPaths, source_video: Path) -> list[Scene] | None:
    if args.crop_mode != "scene-smart" or args.scene_detection == "off":
        return None
    try:
        document, reused = load_or_detect_scenes(
            source_video,
            paths.output_dir,
            threshold=args.scene_threshold,
            min_scene_len=args.scene_min_frames,
            force=args.force_scene_detection,
        )
    except RuntimeError as exc:
        fail(str(exc))
    cache_text = "reused cache" if reused else "generated"
    print(f"Scenes {cache_text}: {len(document.scenes)} shots -> {paths.output_dir / 'scenes.json'}")
    return document.scenes


def run_scenes(args: argparse.Namespace) -> None:
    paths = ProjectPaths.create(args.output_dir)
    source_video = resolve_source_video(args, paths)
    try:
        document, reused = load_or_detect_scenes(
            source_video,
            paths.output_dir,
            threshold=args.scene_threshold,
            min_scene_len=args.scene_min_frames,
            force=args.force_scene_detection,
        )
    except RuntimeError as exc:
        fail(str(exc))
    cache_text = "reused cache" if reused else "generated"
    print(f"Scenes {cache_text}: {len(document.scenes)} shots -> {paths.output_dir / 'scenes.json'}")


def run_transcribe(args: argparse.Namespace) -> None:
    paths = ProjectPaths.create(args.output_dir)
    load_transcript(args, paths)
    print(f"Transcript files: {paths.output_dir / 'transcript.json'} and {paths.output_dir / 'transcript.srt'}")


def run_analyze(args: argparse.Namespace) -> list[ReelSelection]:
    paths = ProjectPaths.create(args.output_dir)
    transcript = load_transcript(args, paths)
    cues = transcript.cues
    chunks = chunk_transcript(
        cues,
        target_seconds=args.chunk_seconds,
        overlap_seconds=args.chunk_overlap_seconds,
    )
    write_json(
        paths.output_dir / "transcript_chunks.json",
        [
            {
                "index": c.index,
                "start": c.start,
                "end": c.end,
                "cue_indexes": c.cue_indexes,
                "text_preview": c.text[:1000],
            }
            for c in chunks
        ],
    )
    print(f"Transcript chunks: {len(chunks)}")

    client = make_client(args)
    candidates = generate_candidates(
        chunks,
        client,
        paths.logs_dir,
        candidates_per_chunk=args.candidates_per_chunk,
        min_duration=args.min_duration,
        max_duration=args.max_duration,
        resume=not args.no_resume,
        force_ollama=args.force_ollama,
    )
    candidates = refine_candidate_boundaries(
        candidates,
        cues,
        transcript.words,
        mode=args.boundary_mode,
        min_duration=args.min_duration,
        target_duration=args.target_duration,
        max_duration=args.max_duration,
        pre_padding=args.pre_padding,
        post_padding=args.post_padding,
    )
    print(f"Candidates generated: {len(candidates)}")
    if not candidates:
        fail("No candidates generated. Check output/logs/ollama_chunk_*.error.txt, update Ollama if structured output is rejected, or test the model with: ollama run qwen3:4b --think=false")

    shortlist = rank_candidates(
        candidates,
        client,
        paths.logs_dir,
        shortlist_count=args.shortlist_count,
        target_count=args.target_count,
        mode=args.ranking_mode,
        resume=not args.no_resume,
        force_ollama=args.force_ollama,
    )
    print(f"Shortlist size: {len(shortlist)}")

    selections = (
        make_default_selections(shortlist, target_count=args.target_count)
        if args.yes
        else interactive_select(shortlist, target_count=args.target_count)
    )
    save_analysis_outputs(paths.output_dir, candidates, shortlist, selections)
    print(f"Selected reels saved: {paths.output_dir / 'selected_reels.json'}")
    return selections


def _parse_seconds(value: Any) -> float:
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        return parse_timecode(value)
    raise ValueError(f"Invalid time value: {value!r}")


def load_selections(path: Path) -> list[ReelSelection]:
    raw = read_json(path)
    if not isinstance(raw, list):
        fail(f"Selected reels JSON must be a list: {path}")
    selections: list[ReelSelection] = []
    for idx, item in enumerate(raw, start=1):
        if not isinstance(item, dict):
            continue
        selections.append(
            ReelSelection(
                id=str(item.get("id") or f"R{idx:02d}"),
                candidate_id=str(item.get("candidate_id") or item.get("id") or f"C{idx:03d}"),
                rank=int(item.get("rank") or idx),
                start=_parse_seconds(item.get("start")),
                end=_parse_seconds(item.get("end")),
                title=str(item.get("title") or "Extrait"),
                hook=str(item.get("hook") or ""),
                reason=str(item.get("reason") or ""),
                transcript_excerpt=str(item.get("transcript_excerpt") or ""),
            )
        )
    return selections


def run_render(args: argparse.Namespace, selections: list[ReelSelection] | None = None) -> None:
    paths = ProjectPaths.create(args.output_dir)
    source_video = resolve_source_video(args, paths)
    transcript = load_transcript(args, paths)
    scenes = load_scenes_for_render(args, paths, source_video)

    if selections is None:
        selected_path = args.selected_reels or (paths.output_dir / "selected_reels.json")
        if not selected_path.exists():
            fail(f"Selected reels file not found: {selected_path}")
        selections = load_selections(selected_path)

    if not selections:
        fail("No selected reels to render.")

    results = render_reels(
        source_video=source_video,
        selections=selections,
        all_cues=transcript.cues,
        output_dir=paths.output_dir / "reels",
        burn_subtitles=not args.no_burn_subtitles,
        subtitle_font_size=args.subtitle_font_size,
        subtitle_margin_v=args.subtitle_margin_v,
        subtitle_wrap_width=args.subtitle_wrap_width,
        subtitle_max_lines=args.subtitle_max_lines,
        subtitle_correction=args.subtitle_correction,
        subtitle_correction_client=make_client(args) if args.subtitle_correction == "ollama" else None,
        force_subtitle_correction=args.force_subtitle_correction,
        crop_mode=args.crop_mode,
        scenes=scenes,
        fps=args.fps,
        end_card_seconds=args.end_card_seconds,
        end_card_style=args.end_card_style,
        end_card_comment_text=args.end_card_comment_text,
        episode_title=args.episode_title,
        youtube_cta=args.youtube_cta,
        youtube_url=args.youtube_url or "",
        crf=args.crf,
        preset=args.preset,
    )
    ok_count = sum(1 for result in results if result.get("status") == "ok")
    print(f"Rendered {ok_count}/{len(results)} reels. Report: {paths.output_dir / 'reels' / 'render_report.json'}")


def run_all(args: argparse.Namespace) -> None:
    selections = run_analyze(args)
    if not args.no_render:
        run_render(args, selections=selections)


def main(argv: list[str] | None = None) -> None:
    configure_console()
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command in {"transcribe", "subtitles"}:
        run_transcribe(args)
    elif args.command == "scenes":
        run_scenes(args)
    elif args.command == "analyze":
        run_analyze(args)
    elif args.command == "render":
        run_render(args)
    elif args.command == "all":
        run_all(args)
    else:
        parser.print_help()
