from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

from .console import configure_console
from .analyzer import (
    generate_candidates,
    interactive_select,
    make_default_selections,
    rank_candidates,
    save_analysis_outputs,
)
from .models import ProjectPaths, ReelSelection
from .ollama_client import OllamaClient
from .renderer import render_reels
from .subtitles import chunk_transcript, load_subtitles, transcript_to_text
from .timecode import parse_timecode
from .utils import fail, read_json, write_json
from .youtube import copy_local_subtitle, download_youtube_video, extract_youtube_subtitles


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="reelmaker",
        description="Generate vertical reels from a local video using YouTube subtitles and Ollama.",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    for name in ["all", "analyze", "render", "subtitles"]:
        add_common_args(sub.add_parser(name))
    return parser


def add_common_args(parser: argparse.ArgumentParser) -> None:
    parser.add_argument("--youtube-url", help="YouTube URL used to extract subtitles, and optionally video.")
    parser.add_argument("--source-video", type=Path, help="Local source video. Preferred for quality.")
    parser.add_argument("--download-video", action="store_true", help="Download YouTube video if --source-video is not provided.")
    parser.add_argument("--subtitle-file", type=Path, help="Existing SRT/VTT file. If omitted, subtitles are extracted from YouTube.")
    parser.add_argument("--subtitle-langs", default="fr.*,fr", help="yt-dlp subtitle language selector. Default avoids en.* to reduce YouTube 429 errors.")
    parser.add_argument("--output-dir", type=Path, default=Path("output"), help="Output directory.")

    parser.add_argument("--ollama-url", default="http://localhost:11434", help="Ollama base URL.")
    parser.add_argument("--model", default="qwen3:4b", help="Ollama model. Default favors speed for local reel selection.")
    parser.add_argument("--temperature", type=float, default=0.2, help="Ollama temperature.")
    parser.add_argument("--num-ctx", type=int, default=16384, help="Ollama context window.")
    parser.add_argument("--ollama-timeout", type=int, default=600, help="Ollama HTTP timeout in seconds.")
    parser.add_argument("--ollama-num-predict", type=int, default=1024, help="Maximum tokens generated by Ollama per request.")
    parser.add_argument("--no-ollama-stream", action="store_true", help="Disable Ollama streaming mode. Streaming is recommended to avoid HTTP read timeouts.")

    parser.add_argument("--target-count", type=int, default=10, help="Final reels count.")
    parser.add_argument("--shortlist-count", type=int, default=20, help="Shortlist count for validation.")
    parser.add_argument("--candidates-per-chunk", type=int, default=3, help="Max candidates proposed per transcript chunk.")
    parser.add_argument("--chunk-seconds", type=int, default=300, help="Transcript chunk size in seconds. Smaller chunks are safer for local models; larger chunks mean fewer Ollama calls.")
    parser.add_argument("--chunk-overlap-seconds", type=int, default=20, help="Transcript overlap between chunks.")
    parser.add_argument("--min-duration", type=int, default=15, help="Minimum reel duration in seconds.")
    parser.add_argument("--max-duration", type=int, default=75, help="Maximum reel duration in seconds.")
    parser.add_argument("--yes", action="store_true", help="Non-interactive: accept top ranked reels.")
    parser.add_argument("--ranking-mode", choices=["local", "ollama"], default="local", help="Ranking strategy. Local is much faster and avoids malformed LLM JSON.")
    parser.add_argument("--no-resume", action="store_true", help="Disable resume/cache of previous Ollama chunk results.")
    parser.add_argument("--force-ollama", action="store_true", help="Ignore cached Ollama chunk/ranking results and recompute.")

    parser.add_argument("--selected-reels", type=Path, help="JSON file generated by analyze; default: output-dir/selected_reels.json.")
    parser.add_argument("--no-render", action="store_true", help="For all/analyze: do not render videos.")
    parser.add_argument("--no-burn-subtitles", action="store_true", help="Render without burning subtitles into video.")
    parser.add_argument("--crf", type=int, default=20, help="FFmpeg x264 CRF, lower means better quality/larger file.")
    parser.add_argument("--preset", default="medium", help="FFmpeg x264 preset.")


def resolve_subtitles(args: argparse.Namespace, paths: ProjectPaths) -> Path:
    if args.subtitle_file:
        if not args.subtitle_file.exists():
            fail(f"Subtitle file not found: {args.subtitle_file}")
        return copy_local_subtitle(args.subtitle_file, paths.subtitles_dir)
    if args.youtube_url:
        return extract_youtube_subtitles(args.youtube_url, paths.subtitles_dir, subtitle_langs=args.subtitle_langs)
    fail("Provide --subtitle-file or --youtube-url.")


def resolve_source_video(args: argparse.Namespace, paths: ProjectPaths) -> Path:
    if args.source_video:
        if not args.source_video.exists():
            fail(f"Source video not found: {args.source_video}")
        return args.source_video
    if args.download_video and args.youtube_url:
        return download_youtube_video(args.youtube_url, paths.source_dir)
    fail("Provide --source-video, or add --download-video with --youtube-url.")


def load_transcript(args: argparse.Namespace, paths: ProjectPaths) -> tuple[Path, list[Any]]:
    subtitle_path = resolve_subtitles(args, paths)
    cues = load_subtitles(subtitle_path)
    if not cues:
        fail(f"No subtitle cues loaded from {subtitle_path}")

    write_json(
        paths.output_dir / "transcript.json",
        [{"index": c.index, "start": c.start, "end": c.end, "text": c.text} for c in cues],
    )
    (paths.output_dir / "transcript.txt").write_text(transcript_to_text(cues), encoding="utf-8")
    print(f"Loaded {len(cues)} subtitle cues from {subtitle_path}")
    return subtitle_path, cues


def make_client(args: argparse.Namespace) -> OllamaClient:
    return OllamaClient(
        base_url=args.ollama_url,
        model=args.model,
        temperature=args.temperature,
        num_ctx=args.num_ctx,
        timeout_seconds=args.ollama_timeout,
        num_predict=args.ollama_num_predict,
        stream=not args.no_ollama_stream,
    )


def run_subtitles(args: argparse.Namespace) -> None:
    paths = ProjectPaths.create(args.output_dir)
    subtitle_path = resolve_subtitles(args, paths)
    print(f"Subtitle file: {subtitle_path}")


def run_analyze(args: argparse.Namespace) -> list[ReelSelection]:
    paths = ProjectPaths.create(args.output_dir)
    _, cues = load_transcript(args, paths)
    chunks = chunk_transcript(
        cues,
        target_seconds=args.chunk_seconds,
        overlap_seconds=args.chunk_overlap_seconds,
    )
    write_json(
        paths.output_dir / "transcript_chunks.json",
        [
            {
                "index": c.index,
                "start": c.start,
                "end": c.end,
                "cue_indexes": c.cue_indexes,
                "text_preview": c.text[:1000],
            }
            for c in chunks
        ],
    )
    print(f"Transcript chunks: {len(chunks)}")

    client = make_client(args)
    candidates = generate_candidates(
        chunks,
        client,
        paths.logs_dir,
        candidates_per_chunk=args.candidates_per_chunk,
        min_duration=args.min_duration,
        max_duration=args.max_duration,
        resume=not args.no_resume,
        force_ollama=args.force_ollama,
    )
    print(f"Candidates generated: {len(candidates)}")
    if not candidates:
        fail("No candidates generated. Check output/logs/ollama_chunk_*.error.txt, reduce --chunk-seconds, increase --ollama-timeout, or test Ollama with: ollama run qwen3:4b")

    shortlist = rank_candidates(
        candidates,
        client,
        paths.logs_dir,
        shortlist_count=args.shortlist_count,
        target_count=args.target_count,
        mode=args.ranking_mode,
        resume=not args.no_resume,
        force_ollama=args.force_ollama,
    )
    print(f"Shortlist size: {len(shortlist)}")

    selections = (
        make_default_selections(shortlist, target_count=args.target_count)
        if args.yes
        else interactive_select(shortlist, target_count=args.target_count)
    )
    save_analysis_outputs(paths.output_dir, candidates, shortlist, selections)
    print(f"Selected reels saved: {paths.output_dir / 'selected_reels.json'}")
    return selections


def _parse_seconds(value: Any) -> float:
    if isinstance(value, (int, float)):
        return float(value)
    if isinstance(value, str):
        return parse_timecode(value)
    raise ValueError(f"Invalid time value: {value!r}")


def load_selections(path: Path) -> list[ReelSelection]:
    raw = read_json(path)
    if not isinstance(raw, list):
        fail(f"Selected reels JSON must be a list: {path}")
    selections: list[ReelSelection] = []
    for idx, item in enumerate(raw, start=1):
        if not isinstance(item, dict):
            continue
        selections.append(
            ReelSelection(
                id=str(item.get("id") or f"R{idx:02d}"),
                candidate_id=str(item.get("candidate_id") or item.get("id") or f"C{idx:03d}"),
                rank=int(item.get("rank") or idx),
                start=_parse_seconds(item.get("start")),
                end=_parse_seconds(item.get("end")),
                title=str(item.get("title") or "Extrait"),
                hook=str(item.get("hook") or ""),
                reason=str(item.get("reason") or ""),
                transcript_excerpt=str(item.get("transcript_excerpt") or ""),
            )
        )
    return selections


def run_render(args: argparse.Namespace, selections: list[ReelSelection] | None = None) -> None:
    paths = ProjectPaths.create(args.output_dir)
    source_video = resolve_source_video(args, paths)
    _, cues = load_transcript(args, paths)

    if selections is None:
        selected_path = args.selected_reels or (paths.output_dir / "selected_reels.json")
        if not selected_path.exists():
            fail(f"Selected reels file not found: {selected_path}")
        selections = load_selections(selected_path)

    if not selections:
        fail("No selected reels to render.")

    results = render_reels(
        source_video=source_video,
        selections=selections,
        all_cues=cues,
        output_dir=paths.output_dir / "reels",
        burn_subtitles=not args.no_burn_subtitles,
        crf=args.crf,
        preset=args.preset,
    )
    ok_count = sum(1 for r in results if r.get("status") == "ok")
    print(f"Rendered {ok_count}/{len(results)} reels. Report: {paths.output_dir / 'reels' / 'render_report.json'}")


def run_all(args: argparse.Namespace) -> None:
    selections = run_analyze(args)
    if not args.no_render:
        run_render(args, selections=selections)


def main(argv: list[str] | None = None) -> None:
    configure_console()
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.command == "subtitles":
        run_subtitles(args)
    elif args.command == "analyze":
        run_analyze(args)
    elif args.command == "render":
        run_render(args)
    elif args.command == "all":
        run_all(args)
    else:
        parser.print_help()
